on:
    push
jobs:
    idle:
        runs-on: ubuntu-latest
        steps:
            -
                run: | 
                    echo Idle Step 1
                    sleep 20
                    echo Wake up
                
